#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Builds src/Localization/protected-words.txt: foreign proper nouns that must keep international
casing when the game upper-cases Turkish text (CITIES: SKYLINES, not CİTİES: SKYLİNES).

The list is derived from the translation itself: a word containing i/I that appears unchanged in
both the English and the Turkish value of the same key was deliberately left untranslated, i.e. it
is a brand, a person or a place name. Words that are also valid Turkish are excluded, so
"Terminal" still becomes "TERMİNAL".

    python tools/build_protected_words.py

Run it after every merge (tools/check_updates.py --merge does that automatically).
"""
import collections
import io
import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
EN_PATH = os.path.join(ROOT, "originals", "en-US", "en-US.json")
TR_PATH = os.path.join(ROOT, "src", "Localization", "tr-TR.json")
OUT_PATH = os.path.join(ROOT, "src", "Localization", "protected-words.txt")

PROTECTED_SPAN = re.compile(r"\{[^{}]*\}|<[^<>]*>")
WORD = re.compile(r"[^\W\d_]+")

# Spelled the same in both languages but genuinely Turkish: these take Turkish casing (FİLM, LİMİT, PARİS).
TURKISH_TOO = {
    "bistro", "bit", "fiber", "film", "ideal", "in", "intermodal", "internet", "kelvin", "ki", "latin",
    "limit", "min", "mineral", "mini", "minimal", "minimum", "panini", "paris", "protein", "terminal",
    "tsunami", "video", "villa",
}

# Brands that only ever occur with a Turkish suffix or inside longer names, so the data cannot reveal them.
ALWAYS = {
    "Cities", "Skylines", "Chirper", "Chirpy", "Paradox", "Interactive", "Unity", "Microsoft", "Windows",
    "PlayStation", "Xbox", "Steam", "Nvidia", "NVidia", "FidelityFX", "DirectX", "Discord", "Twitch",
    "Twitter", "Reddit", "Bilibili", "Instagram", "GitHub", "GitLab", "Crowdin", "Linux", "Intel", "Wiki",
    "Shift", "Visual", "Studio", "Rider", "Login", "Epic", "Tilt", "Editor",
}


def build():
    with io.open(EN_PATH, encoding="utf-8") as fh:
        en = json.load(fh)
    with io.open(TR_PATH, encoding="utf-8") as fh:
        tr = json.load(fh)
    words = collections.Counter()
    for key, english in en.items():
        turkish = tr.get(key)
        if not turkish:
            continue
        english_words = set(WORD.findall(PROTECTED_SPAN.sub(" ", english)))
        for word in set(WORD.findall(PROTECTED_SPAN.sub(" ", turkish))):
            if ("i" in word or "I" in word) and word in english_words:
                words[word] += 1
    result = {w for w in words if w.lower() not in TURKISH_TOO and len(w) > 1}
    result |= ALWAYS
    # matching is case-insensitive at runtime: keep one spelling per word
    unique = {}
    for word in sorted(result):
        unique.setdefault(word.lower(), word)
    return sorted(unique.values(), key=lambda w: w.lower())


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    words = build()
    with io.open(OUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# Generated by tools/build_protected_words.py - do not edit by hand.\n")
        fh.write("# Foreign proper nouns that keep international casing in upper-cased Turkish text.\n")
        fh.write("\n".join(words))
        fh.write("\n")
    print("wrote %s (%d words)" % (os.path.relpath(OUT_PATH, ROOT), len(words)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
